# Generated by Django 6.0.1 on 2026-02-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutorsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('profile_image', models.FileField(upload_to='profile_images/')),
                ('certificate_image', models.FileField(upload_to='certifications/')),
                ('ielts_score', models.FloatField()),
                ('experience', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tutors_profile',
            },
        ),
        migrations.CreateModel(
            name='TutorsTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_time', models.TimeField()),
                ('tutor', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
