# Generated by Django 6.0.2 on 2026-02-25 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors_profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorsprofile',
            options={'verbose_name': 'Tutor profile', 'verbose_name_plural': 'Tutor profiles'},
        ),
        migrations.AlterModelOptions(
            name='tutorstimetable',
            options={'verbose_name': 'Tutors time table', 'verbose_name_plural': 'Tutors time tables'},
        ),
    ]
