# Generated by Django 6.0.2 on 2026-02-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('profile_image', models.FileField(upload_to='profile_images/')),
                ('englishLevel', models.CharField(choices=[('beginner', 'beginner'), ('elementary', 'elementary'), ('pre-intermediate', 'pre-intermediate'), ('intermediate', 'intermediate'), ('upper-intermediate', 'upper-intermediate'), ('advanced', 'advanced'), ('Ielts', 'ielts')])),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'students_profile',
            },
        ),
    ]
