# Generated by Django 6.0.2 on 2026-02-25 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Student profile', 'verbose_name_plural': 'Student profiles'},
        ),
    ]
