# Generated by Django 6.0.2 on 2026-02-24 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('student_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_bookings', to='student_profiles.studentprofile'),
        ),
    ]
