# Generated by Django 6.0.2 on 2026-02-25 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
    ]
