# Generated by Django 6.0.2 on 2026-02-25 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
    ]
