# Generated by Django 6.0.2 on 2026-02-24 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0002_initial'),
        ('tutors_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_reviews', to='tutors_profiles.tutorsprofile'),
        ),
    ]
