# Generated by Django 6.0.2 on 2026-02-25 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
